name: autogis
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - affine=2.3.1
  - alabaster=0.7.12
  - alsa-lib=1.2.7.2
  - anyio=3.6.2
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.8
  - attr=2.5.1
  - attrs=22.1.0
  - babel=2.10.3
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.11.1
  - bleach=5.0.1
  - blosc=1.21.1
  - bokeh=2.4.3
  - boost-cpp=1.78.0
  - branca=0.5.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.9.24
  - cairo=1.16.0
  - certifi=2022.9.24
  - cffi=1.15.1
  - cfitsio=4.1.0
  - charset-normalizer=2.1.1
  - click=8.1.3
  - click-plugins=1.1.1
  - cligj=0.7.2
  - colorama=0.4.6
  - contextily=1.2.0
  - contourpy=1.0.5
  - cryptography=38.0.2
  - curl=7.86.0
  - cycler=0.11.0
  - cykhash=2.0.0
  - cython=0.29.32
  - dbus=1.13.6
  - debugpy=1.6.3
  - decorator=5.1.1
  - defusedxml=0.7.1
  - docutils=0.17.1
  - entrypoints=0.4
  - executing=1.1.1
  - expat=2.5.0
  - fftw=3.3.10
  - fiona=1.8.22
  - flit-core=3.7.1
  - folium=0.13.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.38.0
  - freetype=2.12.1
  - freexl=1.0.6
  - gdal=3.5.2
  - geographiclib=1.52
  - geojson=2.5.0
  - geopandas=0.12.0
  - geopandas-base=0.12.0
  - geopy=2.2.0
  - geos=3.11.0
  - geotiff=1.7.1
  - gettext=0.21.1
  - giflib=5.2.1
  - gitdb=4.0.9
  - gitpython=3.1.29
  - glib=2.74.1
  - glib-tools=2.74.1
  - greenlet=1.1.3.post0
  - gst-plugins-base=1.20.3
  - gstreamer=1.20.3
  - hdf4=4.2.15
  - hdf5=1.12.2
  - icu=70.1
  - idna=3.4
  - imagesize=1.4.1
  - importlib-metadata=5.0.0
  - importlib_resources=5.10.0
  - ipykernel=6.16.2
  - ipython=8.6.0
  - ipython_genutils=0.2.0
  - jack=1.9.21
  - jedi=0.18.1
  - jinja2=3.1.2
  - joblib=1.2.0
  - jpeg=9e
  - json-c=0.16
  - json5=0.9.5
  - jsonschema=4.16.0
  - jupyter-cache=0.5.0
  - jupyter-server-mathjax=0.2.6
  - jupyter_client=7.4.4
  - jupyter_core=4.11.1
  - jupyter_server=1.21.0
  - jupyterlab=3.5.0
  - jupyterlab-git=0.39.3
  - jupyterlab-markup=1.0.1
  - jupyterlab-myst=0.1.6
  - jupyterlab_pygments=0.2.2
  - jupyterlab_server=2.16.1
  - jupytext=1.14.0
  - kealib=1.4.15
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.19.3
  - lame=3.100
  - lcms2=2.13.1
  - ld_impl_linux-64=2.39
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcap=2.66
  - libcblas=3.9.0
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcups=2.3.3
  - libcurl=7.86.0
  - libdap4=3.20.6
  - libdb=6.2.32
  - libdeflate=1.14
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.4.2
  - libflac=1.4.2
  - libgcc-ng=12.2.0
  - libgdal=3.5.2
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libglib=2.74.1
  - libgomp=12.2.0
  - libiconv=1.17
  - libkml=1.3.0
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libnetcdf=4.8.1
  - libnghttp2=1.47.0
  - libnsl=2.0.0
  - libogg=1.3.4
  - libopenblas=0.3.21
  - libopus=1.3.1
  - libpng=1.6.38
  - libpq=14.5
  - librttopo=1.1.0
  - libsndfile=1.1.0
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libspatialite=5.0.1
  - libsqlite=3.39.4
  - libssh2=1.10.0
  - libstdcxx-ng=12.2.0
  - libtiff=4.4.0
  - libtool=2.4.6
  - libudev1=251
  - libuuid=2.32.1
  - libvorbis=1.3.7
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxkbcommon=1.0.3
  - libxml2=2.10.3
  - libzip=1.9.2
  - libzlib=1.2.13
  - lz4-c=1.9.3
  - mapclassify=2.4.3
  - markdown-it-py=2.1.0
  - markupsafe=2.1.1
  - matplotlib=3.6.1
  - matplotlib-base=3.6.1
  - matplotlib-inline=0.1.6
  - mdit-py-plugins=0.3.1
  - mdurl=0.1.0
  - mercantile=1.2.1
  - mistune=2.0.4
  - mpg123=1.30.2
  - munch=2.5.0
  - munkres=1.1.4
  - mysql-common=8.0.31
  - mysql-libs=8.0.31
  - myst-nb=0.17.1
  - myst-parser=0.18.1
  - nbclassic=0.4.7
  - nbclient=0.5.13
  - nbconvert=7.2.3
  - nbconvert-core=7.2.3
  - nbconvert-pandoc=7.2.3
  - nbdime=3.1.1
  - nbformat=5.7.0
  - ncurses=6.3
  - nest-asyncio=1.5.6
  - networkx=2.8.7
  - notebook=6.4.12
  - notebook-shim=0.2.0
  - nspr=4.32
  - nss=3.78
  - numpy=1.23.4
  - openjpeg=2.5.0
  - openssl=1.1.1q
  - osmnx=1.2.2
  - packaging=21.3
  - pandas=1.5.1
  - pandoc=2.19.2
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pcre=8.45
  - pcre2=10.37
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.2.0
  - pip=22.3
  - pixman=0.40.0
  - pkgutil-resolve-name=1.3.10
  - ply=3.11
  - poppler=22.10.0
  - poppler-data=0.4.11
  - postgresql=14.5
  - proj=9.1.0
  - prometheus_client=0.15.0
  - prompt-toolkit=3.0.31
  - psutil=5.9.3
  - psycopg2=2.9.3
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pulseaudio=14.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pydata-sphinx-theme=0.8.1
  - pygeos=0.13
  - pygments=2.13.0
  - pyopenssl=22.1.0
  - pyparsing=3.0.9
  - pyproj=3.4.0
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyrobuf=0.9.3
  - pyrosm=0.6.1
  - pyrsistent=0.18.1
  - pysocks=1.7.1
  - python=3.10.6
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-rapidjson=1.9
  - python_abi=3.10
  - pytz=2022.5
  - pyyaml=6.0
  - pyzmq=24.0.1
  - qt-main=5.15.6
  - rasterio=1.3.3
  - readline=8.1.2
  - requests=2.28.1
  - rtree=1.0.1
  - scikit-learn=1.1.3
  - scipy=1.9.3
  - send2trash=1.8.0
  - setuptools=65.5.0
  - shapely=1.8.5
  - sip=6.7.3
  - six=1.16.0
  - smmap=3.0.5
  - snappy=1.1.9
  - sniffio=1.3.0
  - snowballstemmer=2.2.0
  - snuggs=1.4.7
  - soupsieve=2.3.2.post1
  - sphinx=4.5.0
  - sphinx-book-theme=0.3.3
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=2.0.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.5
  - sqlalchemy=1.4.42
  - sqlite=3.39.4
  - stack_data=0.5.1
  - tabulate=0.9.0
  - terminado=0.17.0
  - threadpoolctl=3.1.0
  - tiledb=2.11.3
  - tinycss2=1.2.1
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - tornado=6.2
  - traitlets=5.5.0
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - tzcode=2022e
  - tzdata=2022e
  - unicodedata2=14.0.0
  - urllib3=1.26.11
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.4.1
  - wheel=0.37.1
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xerces-c=3.2.4
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xyzservices=2022.9.0
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.10.0
  - zlib=1.2.13
  - zstd=1.5.2
