name: autogis-2

channels:
    - conda-forge

dependencies:
    - python=3.10

    # sphinx + dependencies
    - myst-nb
    - sphinx
    - sphinx-book-theme
    - sphinx-thebe

    # lessons
    - geopandas
